# Jekyll configuration file

title: Aletha Labs
description: A blog about Aletha Labs projects and insights
baseurl: ""
url: "http://alethalabs.com"

# Build settings
markdown: kramdown

# Theme settings
theme: minima
